### ISSUE TITLE
Default JSON TypeInfoResolver

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dotnet#2788]
Out of the box, Sentry.init() doesn't work for apps compiled with native AOT. The following console app fails to serialize with the error later below:
```c#
using Sentry;

// Initialize the Sentry SDK.  (It is not necessary to dispose it.)
SentrySdk.Init(options =>
{
    options.Dsn = Environment.GetCommandLineArgs()[1];
    options.Debug = true;
});

throw new ApplicationException("Something happened!");
```

```
System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled() + 0x2b
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer() + 0x31
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type) + 0x2a
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions) + 0x25
   at Sentry.Internal.Extensions.JsonExtensions.InternalSerializeToUtf8Bytes(Object) + 0x6a
   at Sentry.Internal.Extensions.JsonExtensions.WriteDynamicValue(Utf8JsonWriter, Object, IDiagnosticLogger) + 0x41b
   at Sentry.Internal.Extensions.JsonExtensions.WriteDynamic(Utf8JsonWriter, String, Object, IDiagnosticLogger) + 0x4b
```

**Comment by vaind** [comment]
Actually the AotHelper doesn't work at all. Fixed here: https://github.com/getsentry/sentry-dotnet/pull/2781/commits/300db5a39cd4ed79b6169b9467aa946a221fc364

**Comment by vaind** [comment]
Actually, this is an issue, regardless of the AotHelper.

In JIT, the serialization throws above exception. This can be easily verified by running:
```
cd samples/Sentry.Samples.Console.Basic
dotnet run --framework net8.0
```

**Comment by jamescrosswell** [comment]
Interesting. It doesn't occur when running `Sentry.Samples.Console.Basic` from Rider as part of the `Sentry-CI-Build-macOS` solution filter. 🤔 

However if does still occur if I add `<Import Project="..\Directory.Build.props" />` to `Sentry.Samples.Console.Basic.csproj` to make sure the same properties are set in both instances and then open/run `Sentry.Samples.Console.Basic.csproj` directly (outside the solution filter).

**Comment by jamescrosswell** [comment]
OK, I found it... We have a WriteDictionary method that's not using the new JSON serialization:
https://github.com/getsentry/sentry-dotnet/blob/8f167a052b2bd71e7b35aceb5652f993ce9b4e5c/src/Sentry/Internal/Extensions/JsonExtensions.cs#L259

I should be able to fix this easily enough. It does highlight the need to get some integration tests in place though... so maybe I'll prioritize that next.

**Comment by vaind** [comment]
> dotnet run --framework net8.0 

Just to reiterrate what was said in the PR (#2799) - `dotnet run` is never an AOT compiled app

**Comment by vaind** [comment]
Oh, I think I see what is the problem. It's not that it runs an AOT build, it's that just setting that at some point you'll want to publish AOT, it disables reflection-based serialization altogether. Which makes sense because that makes you fix your app before publishing.

**Comment by vaind** [comment]
I've found a solution and will create a PR shortly
