### ISSUE TITLE
Get this when I try to use sentry: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.1.0, Culture=neutral, 

### ISSUE THREAD

**Issue by R10-Rasmus** [getsentry/sentry-dotnet#345]
I use:

[x ] ASP.NET Core
Please mark the type of the runtime used:

[x ] .NET Core
Version: 3.1
Please mark the NuGet packages used:

[ x] Sentry 2.0.0-beta8

My code is:
public static IHostBuilder CreateHostBuilder(string[] args) =>
Host.CreateDefaultBuilder(args)
.ConfigureWebHostDefaults(webBuilder =>
{
webBuilder.UseSentry();
webBuilder.UseStartup();
});

When I try to call a controller method I get:
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Error: Connection ID "18374686502757072928", Request ID "80000021-0005-ff00-b63f-84710c7967bb": An unhandled exception was thrown by the application.

System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 10.2048ms 500

**Comment by llamanna** [comment]
In this issue https://github.com/getsentry/sentry-dotnet/issues/311 Is was  suggest to use the latest beta.  I did this and it works.
@bruno-garcia  do you know when will be available the stable of  version  2?

**Comment by bruno-garcia** [comment]
@llamanna I've just released it. I hope to get some feedback.
I was not able to repro this issue on the latest version.

@R10-Rasmus could you please share a repro?

**Comment by R10-Rasmus** [comment]
@bruno-garcia I have now tried version 2.0.1 and I still get the same problem:
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

This is the code I use:
 public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseSentry();// FIX use Sentry when it works on 3.1 UseSentry breaks we get:
                    //Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
                    //at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
                    //see issue https://github.com/getsentry/sentry-dotnet/issues/345 
                    webBuilder.UseStartup<Startup>();
                });

**Comment by llamanna** [comment]
@bruno-garcia thank you! It workd fine!
@R10-Rasmus Have you cleaned the packages folder? If you are working with Visual studio you can check if are loaded the right version of dll in the modules windows.
![image](https://user-images.githubusercontent.com/9365207/73242208-9ba5d580-41a4-11ea-87e5-d8727e8628d3.png)

**Comment by R10-Rasmus** [comment]
I was running a mix of version 1 and 2. 
I am now only using version 2, and it works. Thanks 👍
